### ISSUE TITLE
Error when trying to add a commit message

### ISSUE THREAD

**Issue by guilherme-jsv-soares** [samuellawrentz/jira-git-commit-helper#2]
Hi Samuel
Thanks for creating this extension. It's something that I really would like to use.

The problem I'm having is that I'm always getting the error in this image:
![Screenshot 2023-12-19 at 15 43 04](https://github.com/samuellawrentz/jira-git-commit-helper/assets/35031275/e76a6f9c-c64c-4030-a7db-0606aedb04d7)

I tried various urls from my JIRA project but none of them worked.
Do you have an idea of why this is happening?

**Comment by samuellawerentz** [comment]
Thanks for using this extension. Mostly it will happen if URL or email is not proper. 

1. Enter your work email
2. Enter the JIRA token
3. Enter company URL (without ending slash)
  Eg: https://your-company.atlassian.net

I'll release a new version in some days, you can update and try afterwards.

**Comment by samuellawrentz** [comment]
Can you try the latest version? Closing this for now. Please reopen if issue persist.

**Comment by guilherme-jsv-soares** [comment]
Hi Samuel
Thanks for the update. It seems to have fixed the problem I've reported.

A small now seems to be that it never returns any issues. I think it's due to your query having `project = CNTO` param.
I've tested queries without it and everything works fine.

Can you do this small adjustment please?

**Comment by samuellawrentz** [comment]
Hello, 
Apologies! That's a silly mistake from my side. Thank you for looking into the project and highlighting it. I'm planning to remove the `project = ` from the query so that all the tickets assigned to you will be listed. 

Please let me know if that works for you.

Do you think, the JQL query also should be received from the user similar to the user name and token etc?

**Comment by samuellawrentz** [comment]
I have published a new version for this v1.0.2. Please check and let me know your views. Thanks much.

**Comment by samuellawrentz** [comment]
https://github.com/samuellawrentz/jira-git-commit-helper/releases/tag/v1.0.2

**Comment by guilherme-jsv-soares** [comment]
> Hello, Apologies! That's a silly mistake from my side. Thank you for looking into the project and highlighting it. I'm planning to remove the `project = ` from the query so that all the tickets assigned to you will be listed.
> 
> Please let me know if that works for you.
> 
> Do you think, the JQL query also should be received from the user similar to the user name and token etc?

That would be great!! Although it should be optional because not everyone is aware of what JQL is.

**Comment by guilherme-jsv-soares** [comment]
> I have published a new version for this v1.0.2. Please check and let me know your views. Thanks much.

It's working!!! It's great, thank you for your work.
