### ISSUE TITLE
Quick review after working with it for 1+ monhts

### ISSUE THREAD

**Issue by guilherme-jsv-soares** [samuellawrentz/jira-git-commit-helper#5]
Hi Samuel
Thanks again for your work in this extension.

After using it for a while now I can say it's great and simplifies my workflow a lot.

One update I would love to see is a way of defining what to write in the commit box after we select the ticket.
I say this because in most cases I just want to copy the JIRA ticket number and title to the commit box and not add my own comment.

If a full settings definition of how the message should look it's too much work I would suggest that when we select a ticket from the list and the "Select type of the changes" options appear (Bug Fix, Updates, Optimization....) add another one to the bottom that just says "Copy ticket number and title" that just copies the ticket number and title to the commit box.

Thanks again.
GS

**Comment by samuellawrentz** [comment]
Hi @guilherme-jsv-soares 

Thank you for the feedback! I'm glad that this extension helped you..!

Sure, what you are suggesting would be a good solution. 

We'll provide one more option - "Use ticket title" and it should populate the commit box with the ticket number and title. 

I will let you know once I push this change!

**Comment by samuellawrentz** [comment]
Have added this change, can you please try it out and let me know? Update to the latest version from VSCode Extension Page. This change is in v1.0.4.

![image](https://github.com/samuellawrentz/jira-git-commit-helper/assets/24652924/7b9d89c8-fbd2-4abc-9d83-0470918e7025)

**Comment by guilherme-jsv-soares** [comment]
It's perfect. Thank you so much for your quick response.
